### PR TITLE
docs: Solve eslint prompt problem

### PR DESCRIPTION
**Pull request by Otto-J**
When I used eslint, I found that there was a problem, and I followed the vue document to supplement the eslint rules. Add to readme

### CODE REVIEW

**Comment by Otto-J** [comment]
😯 oh no , same #5

**Comment by Otto-J** [comment]
Accept or close, it’s up to you. 😊

**Comment by antfu** [comment]
Awesome, thanks for collect them out! While this is a good approach, I'd love to provide a eslint preset under the package as `vue-global-api/eslint-config` so user could simply extend it. Meanwhile, we could update the `generate.ts` file to keep the configure always up to date with the installed version.

If you would like to take the approach, please feel free to do so, or I can do that later as well. Thanks

**Comment by Otto-J** [comment]
on,yes. this package include a eslint config. i will try to do today

**Comment by antfu** [comment]
#13

**Pull request closed without merging**
